name: build (arm64)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Pull ARM64 image
      run: |
        docker pull gemesa/arm64:latest
        
    - name: Run ARM64 container
      run: |
        docker run --platform=linux/arm64 \
          --rm \
          -v "${{ github.workspace }}":/workspace \
          gemesa/arm64:latest \
          make arm64
