name: build (x64)

on: [push]

jobs:
  build-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install prerequisites
        run: |
          rustup target add x86_64-pc-windows-gnu
          sudo apt-get install gcc-mingw-w64 nasm llvm

      - name: Build
        run: |
          make x64
          make x64-lab
