name: build (arm64)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Build ARM64 image
      run: |
        docker build --platform=linux/arm64 -t arm64-env .
        
    - name: Run ARM64 container
      run: |
        docker run --platform=linux/arm64 \
          --rm \
          -v "${{ github.workspace }}":/workspace \
          arm64-env \
          make arm64
